# Generated by Django 4.2.3 on 2024-04-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_name'),
        ('assets', '0002_asset_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='organizations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
