# Generated by Django 4.2.3 on 2024-04-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='organizations',
            new_name='organization',
        ),
    ]
